[package]
name = "temper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = {version="0.8.2",features=["v4"]}
rand_chacha = "0.3.1"
rand = "0.8.5"
threadpool = "1.8.1"
chrono = "0.4.19"